// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PageDocumentDataSlicesSlice =
  | RichTextSlice
  | HeroSectionSlice
  | AboutSectionSlice
  | ServicesSectionSlice
  | TeamSectionSlice
  | ClinicGallerySlice
  | EquipmentSectionSlice
  | VideoSectionSlice
  | ContactSectionSlice
  | LocationMapSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  title: prismic.TitleField;
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice>;
  meta_title: prismic.KeyTextField;
  meta_description: prismic.KeyTextField;
  meta_image: prismic.ImageField<never>;
}

export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

/**
 * Item in *Galería → Imágenes*
 */
export interface GalleryDocumentDataImagesItem {
  image: prismic.ImageField<never>;
  video: prismic.LinkToMediaField;
}

/**
 * Content for Galería documents
 */
interface GalleryDocumentData {
  images: prismic.GroupField<Simplify<GalleryDocumentDataImagesItem>>;
}

export type GalleryDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<GalleryDocumentData>,
    "gallery",
    Lang
  >;

export type AllDocumentTypes = PageDocument | GalleryDocument;

// --- RichText Slice ---

export interface RichTextSliceDefaultPrimary {
  content: prismic.RichTextField;
}

export type RichTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<RichTextSliceDefaultPrimary>,
  never
>;

type RichTextSliceVariation = RichTextSliceDefault;

export type RichTextSlice = prismic.SharedSlice<
  "rich_text",
  RichTextSliceVariation
>;

// --- HeroSection Slice ---

export interface HeroSectionSliceDefaultPrimary {
  heading: prismic.RichTextField;
  tagline: prismic.RichTextField;
  cta_label: prismic.KeyTextField;
  cta_link: prismic.LinkField;
  cta_secondary_label: prismic.KeyTextField;
  cta_secondary_link: prismic.LinkField;
  background_image: prismic.ImageField<never>;
  background_video: prismic.LinkToMediaField;
}

export type HeroSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSectionSliceDefaultPrimary>,
  never
>;

type HeroSectionSliceVariation = HeroSectionSliceDefault;

export type HeroSectionSlice = prismic.SharedSlice<
  "hero_section",
  HeroSectionSliceVariation
>;

// --- AboutSection Slice ---

export interface AboutSectionSliceDefaultPrimary {
  section_id: prismic.KeyTextField;
  eyebrow: prismic.KeyTextField;
  heading: prismic.RichTextField;
  description: prismic.RichTextField;
}

export interface AboutSectionSliceDefaultItem {
  pillar_title: prismic.KeyTextField;
  pillar_description: prismic.RichTextField;
}

export type AboutSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AboutSectionSliceDefaultPrimary>,
  Simplify<AboutSectionSliceDefaultItem>
>;

type AboutSectionSliceVariation = AboutSectionSliceDefault;

export type AboutSectionSlice = prismic.SharedSlice<
  "about_section",
  AboutSectionSliceVariation
>;

// --- ServicesSection Slice ---

export interface ServicesSectionSliceDefaultPrimary {
  section_id: prismic.KeyTextField;
  eyebrow: prismic.KeyTextField;
  heading: prismic.RichTextField;
  description: prismic.RichTextField;
}

export interface ServicesSectionSliceDefaultItem {
  service_name: prismic.KeyTextField;
  service_description: prismic.RichTextField;
}

export type ServicesSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ServicesSectionSliceDefaultPrimary>,
  Simplify<ServicesSectionSliceDefaultItem>
>;

type ServicesSectionSliceVariation = ServicesSectionSliceDefault;

export type ServicesSectionSlice = prismic.SharedSlice<
  "services_section",
  ServicesSectionSliceVariation
>;

// --- TeamSection Slice ---

export interface TeamSectionSliceDefaultPrimary {
  section_id: prismic.KeyTextField;
  eyebrow: prismic.KeyTextField;
  heading: prismic.RichTextField;
}

export interface TeamSectionSliceDefaultItem {
  name: prismic.KeyTextField;
  role: prismic.KeyTextField;
  credentials: prismic.KeyTextField;
  bio: prismic.RichTextField;
  photo: prismic.ImageField<never>;
  photo_video: prismic.LinkToMediaField;
}

export type TeamSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TeamSectionSliceDefaultPrimary>,
  Simplify<TeamSectionSliceDefaultItem>
>;

type TeamSectionSliceVariation = TeamSectionSliceDefault;

export type TeamSectionSlice = prismic.SharedSlice<
  "team_section",
  TeamSectionSliceVariation
>;

// --- ClinicGallery Slice ---

export interface ClinicGallerySliceDefaultPrimary {
  section_id: prismic.KeyTextField;
  eyebrow: prismic.KeyTextField;
  heading: prismic.RichTextField;
}

export type ClinicGallerySliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ClinicGallerySliceDefaultPrimary>,
  never
>;

type ClinicGallerySliceVariation = ClinicGallerySliceDefault;

export type ClinicGallerySlice = prismic.SharedSlice<
  "clinic_gallery",
  ClinicGallerySliceVariation
>;

// --- EquipmentSection Slice ---

export interface EquipmentSectionSliceDefaultPrimary {
  section_id: prismic.KeyTextField;
  eyebrow: prismic.KeyTextField;
  heading: prismic.RichTextField;
  description: prismic.RichTextField;
  coming_soon_label: prismic.KeyTextField;
}

export interface EquipmentSectionSliceDefaultItem {
  equipment_name: prismic.KeyTextField;
  equipment_description: prismic.RichTextField;
  equipment_image: prismic.ImageField<never>;
  equipment_video: prismic.LinkToMediaField;
}

export type EquipmentSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<EquipmentSectionSliceDefaultPrimary>,
  Simplify<EquipmentSectionSliceDefaultItem>
>;

type EquipmentSectionSliceVariation = EquipmentSectionSliceDefault;

export type EquipmentSectionSlice = prismic.SharedSlice<
  "equipment_section",
  EquipmentSectionSliceVariation
>;

// --- VideoSection Slice ---

export interface VideoSectionSliceDefaultPrimary {
  section_id: prismic.KeyTextField;
  eyebrow: prismic.KeyTextField;
  heading: prismic.RichTextField;
  description: prismic.RichTextField;
  poster_image: prismic.ImageField<never>;
}

export interface VideoSectionSliceDefaultItem {
  video_file: prismic.LinkToMediaField;
  video_title: prismic.KeyTextField;
}

export type VideoSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<VideoSectionSliceDefaultPrimary>,
  Simplify<VideoSectionSliceDefaultItem>
>;

type VideoSectionSliceVariation = VideoSectionSliceDefault;

export type VideoSectionSlice = prismic.SharedSlice<
  "video_section",
  VideoSectionSliceVariation
>;

// --- ContactSection Slice ---

export interface ContactSectionSliceDefaultPrimary {
  section_id: prismic.KeyTextField;
  heading: prismic.RichTextField;
  booking_label: prismic.KeyTextField;
  doctoralia_widget_url: prismic.KeyTextField;
  doctoralia_facility: prismic.KeyTextField;
  map_embed_url: prismic.KeyTextField;
  label_address: prismic.KeyTextField;
  address: prismic.RichTextField;
  label_phone: prismic.KeyTextField;
  phone: prismic.KeyTextField;
  label_email: prismic.KeyTextField;
  email: prismic.KeyTextField;
  label_hours: prismic.KeyTextField;
  hours_weekday: prismic.KeyTextField;
  hours_saturday: prismic.KeyTextField;
  doctoralia_link: prismic.LinkField;
  doctoralia_label: prismic.KeyTextField;
  directions_link: prismic.LinkField;
  directions_label: prismic.KeyTextField;
}

export type ContactSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContactSectionSliceDefaultPrimary>,
  never
>;

type ContactSectionSliceVariation = ContactSectionSliceDefault;

export type ContactSectionSlice = prismic.SharedSlice<
  "contact_section",
  ContactSectionSliceVariation
>;

// --- LocationMap Slice ---

export interface LocationMapSliceDefaultPrimary {
  section_id: prismic.KeyTextField;
  heading: prismic.RichTextField;
  map_embed_url: prismic.KeyTextField;
}

export type LocationMapSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<LocationMapSliceDefaultPrimary>,
  never
>;

type LocationMapSliceVariation = LocationMapSliceDefault;

export type LocationMapSlice = prismic.SharedSlice<
  "location_map",
  LocationMapSliceVariation
>;

// --- Module augmentation ---

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      GalleryDocument,
      GalleryDocumentData,
      GalleryDocumentDataImagesItem,
      AllDocumentTypes,
      RichTextSlice,
      RichTextSliceDefaultPrimary,
      RichTextSliceVariation,
      RichTextSliceDefault,
      HeroSectionSlice,
      HeroSectionSliceDefaultPrimary,
      HeroSectionSliceVariation,
      HeroSectionSliceDefault,
      AboutSectionSlice,
      AboutSectionSliceDefaultPrimary,
      AboutSectionSliceDefaultItem,
      AboutSectionSliceVariation,
      AboutSectionSliceDefault,
      ServicesSectionSlice,
      ServicesSectionSliceDefaultPrimary,
      ServicesSectionSliceDefaultItem,
      ServicesSectionSliceVariation,
      ServicesSectionSliceDefault,
      TeamSectionSlice,
      TeamSectionSliceDefaultPrimary,
      TeamSectionSliceDefaultItem,
      TeamSectionSliceVariation,
      TeamSectionSliceDefault,
      ClinicGallerySlice,
      ClinicGallerySliceDefaultPrimary,
      ClinicGallerySliceVariation,
      ClinicGallerySliceDefault,
      EquipmentSectionSlice,
      EquipmentSectionSliceDefaultPrimary,
      EquipmentSectionSliceDefaultItem,
      EquipmentSectionSliceVariation,
      EquipmentSectionSliceDefault,
      VideoSectionSlice,
      VideoSectionSliceDefaultPrimary,
      VideoSectionSliceDefaultItem,
      VideoSectionSliceVariation,
      VideoSectionSliceDefault,
      ContactSectionSlice,
      ContactSectionSliceDefaultPrimary,
      ContactSectionSliceVariation,
      ContactSectionSliceDefault,
      LocationMapSlice,
      LocationMapSliceDefaultPrimary,
      LocationMapSliceVariation,
      LocationMapSliceDefault,
    };
  }
}
