// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  rich_text: dynamic(() => import("./RichText")),
  hero_section: dynamic(() => import("./HeroSection")),
  about_section: dynamic(() => import("./AboutSection")),
  services_section: dynamic(() => import("./ServicesSection")),
  team_section: dynamic(() => import("./TeamSection")),
  clinic_gallery: dynamic(() => import("./ClinicGallery")),
  equipment_section: dynamic(() => import("./EquipmentSection")),
  video_section: dynamic(() => import("./VideoSection")),
  contact_section: dynamic(() => import("./ContactSection")),
  location_map: dynamic(() => import("./LocationMap")),
};
